name: Build release

on: [ workflow_dispatch ]

jobs:
    build:
        name: Build release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Build
              shell: pwsh
              run: |
                $version = (Select-String -Path DiscordWebhook.psd1 -Pattern "ModuleVersion\s*=\s*'\s*([0-9]+\.[0-9+]\.[0-9]+)\s*'").Matches[0].Groups[1].Value
                "RELEASE_VERSION=$($version)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
                New-Item -Path build -Type Directory | Out-Null
                New-Item -Path build/DiscordWebhook -Type Directory | Out-Null
                Copy-Item -Path *.ps*1 -Destination build/DiscordWebhook | Out-Null
            - name: Upload release package
              uses: actions/upload-artifact@v4
              with:
                name: discord-webhook-${{env.RELEASE_VERSION}}
                path: |
                    build/
        